# Generated by Django 4.0.4 on 2022-05-01 17:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=500, unique=True, verbose_name='Email пользователя')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль пользователя')),
                ('latitude', models.CharField(max_length=255, verbose_name='Широта')),
                ('longitude', models.CharField(max_length=255, verbose_name='Долгота')),
                ('cart_number', models.CharField(max_length=255, verbose_name='Номер карты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, verbose_name='Блюдо')),
                ('photo', models.CharField(max_length=5000, verbose_name='Изображение блюда')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('category_name', models.CharField(max_length=500, verbose_name='Категория блюда')),
                ('restaurant_name', models.CharField(max_length=255, verbose_name='Название ресторана')),
                ('restaurant_logo', models.CharField(max_length=5000, verbose_name='Лого ресторана')),
                ('restaurant_category', models.CharField(max_length=255, verbose_name='Название категорий ресторана')),
                ('restaurant_delivery', models.CharField(max_length=255, verbose_name='Время доставки')),
                ('restaurant_delivery_price', models.IntegerField(verbose_name='Сумма доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюды',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(verbose_name='Общая сумма')),
                ('phone_number', models.CharField(max_length=300, verbose_name='Номер телефона')),
                ('purchase_time', models.DateTimeField(auto_now_add=True, verbose_name='Время покупки')),
                ('success', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('buyer', models.ForeignKey(on_delete=models.SET(0), to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.CharField(max_length=200, verbose_name='Стоимость')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товары в корзине',
                'verbose_name_plural': 'Список товаров',
            },
        ),
    ]
